### ISSUE TITLE
关于smooth max的消融实验

### ISSUE THREAD

**Issue by chenslcool** [wangjuan313/wsis-boundingbox#1]
nice job! 但是关于paper我有个疑问：
在验证smooth  maximum有效性的时候，table 2中，为何没有比较两种方法和普通max的对比结果？按理说应该要的，就像table1要比较MIL baseline一样。
谢谢！

**Comment by wangjuan313** [comment]
Thanks for your interest in our work. MIL baseline in Table 1 uses settings
of theta=0 and max function. It is also the baseline for the results in
Table 2, which consider theta=0 and smooth maximum approximation.

**Comment by chenslcool** [comment]
Ok, thanks
