### ISSUE TITLE
ATLAS数据集

### ISSUE THREAD

**Issue by meiluzhu** [wangjuan313/wsis-boundingbox#2]
您好，非常棒的work。我下载ATLAS 1.1之后，输入给的password总是报错。可以共享一下ATLAS数据集吗？

**Comment by wangjuan313** [comment]
Regrading this issue, you can always contact the authors of the dataset. I have no permissions to share this dataset in public. However, I would be very happy to help you to download it. Please email me if you have any problems with it. Thanks.

**Comment by Huster-Hq** [comment]
> Regrading this issue, you can always contact the authors of the dataset. I have no permissions to share this dataset in public. However, I would be very happy to help you to download it. Please email me if you have any problems with it. Thanks.

Can u help me to download it, too? I already emailed you.
