### ISSUE TITLE
关于实验结果的问题

### ISSUE THREAD

**Issue by czifan** [wangjuan313/wsis-boundingbox#3]
您好，感谢您分享有趣的工作！
我尝试按照readme实验PROMISE12数据集上的性能，结果如下图：
![image](https://user-images.githubusercontent.com/24490441/158183816-534fe277-24f2-4e22-aede-f431714d059f.png)
有部分实验结果和文中的数值对不上，例如全监督模型的性能远高于文中报告的数值，residual_parallel_approx_focal_40_20_explogs=8_unary_pair的三个消融结果的趋势也与文中不一致。想问下有可能是什么原因造成的，我猜想是否有可能是train和val划分产生的差异，我这边划分出来的val是Case 02/16/19/24/25/26/30/31/32/48。
期望能够收到您的回复！

**Comment by wangjuan313** [comment]
The dataset split is same. We used the same validation subset.

I noticed that your models were optimal at epoch=49 and threshold=0.5 in all settings. This is different in my experiments. Did you make any changes in the experiment setups? My reports were as follows for your reference. Hope this is helpful. 

<img width="515" alt="promise" src="https://user-images.githubusercontent.com/15615615/158247519-6f070301-84b2-4532-b002-83dd76ed3997.png">

**Comment by czifan** [comment]
Thank you for your reply. 
However, when I keep the same setting with your experiments, the result is as shown below.
![image](https://user-images.githubusercontent.com/24490441/158350673-fbedf4a2-fcee-490c-bf87-9ff8ba3fbf54.png)
The performance is still inconsistent with the paper (such as "residual_all_fs", its accuray is 0.977 in my experimental results but 0.894 in the paper). I'm not sure what went wrong.

**Comment by wangjuan313** [comment]
Interesting. Now the comparison among different methods has similar trend. However, your models got much higher 3d dice coefficients, and the difference in performance seems significant. Reference [5] in the paper reported similar performance (3d dice = 0.901) for full supervision in the same validation subset. 

Noticed that your models were optimal at larger epoch, this might be the reason for higher performance. However, it is still not convince evidence for such higher performance if the same settings were used. Did you make any changes in the experimental setups? I would be happy to replicate your experiments if any changes were made.

**Comment by czifan** [comment]
> Interesting. Now the comparison among different methods has similar trend. However, your models got much higher 3d dice coefficients, and the difference in performance seems significant. Reference [5] in the paper reported similar performance (3d dice = 0.901) for full supervision in the same validation subset.
> 
> Noticed that your models were optimal at larger epoch, this might be the reason for higher performance. However, it is still not convince evidence for such higher performance if the same settings were used. Did you make any changes in the experimental setups? I would be happy to replicate your experiments if any changes were made.

Thanks for your reply. I believe I have not made any changes in the experimental setups. And I have sent my code with data to your email, which contains the details for my experiments. Looking forward to hearing from you. thanks~
